# Change these first
owner: plakio # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sitio web
    url: https://plak.io/
  - name: Portal de soporte
    url: https://soporte.plak.io/
  - name: Comunidad de usuarios
    url: https://comunidad.plak.io/
  - name: Plak CLI
    url: https://plak.sh/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.plak.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado de los servicios
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Estados
      href: /
    - title: Soporte
      href: https://soporte.plak.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
