# Change these first
owner: plakio # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"          
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* * * * *"

sites:
  - name: Sitio web
    url: https://plak.io/
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  - name: Panel de control
    url: https://cloud.plak.io/login
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  - name: Portal de soporte
    url: https://soporte.plak.io/
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  - name: Comunidad de usuarios
    url: https://comunidad.plak.io/
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  - name: NSLookup
    url: https://lookup.plak.io/
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  - name: Plak CLI
    url: https://plak.sh/
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plakcli-icon.svg

assignees:
  - oscarhugopaz
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  cname: status.plak.io
  theme: light
  logoUrl: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-logo.svg
  favicon: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.png
  faviconSvg: https://raw.githubusercontent.com/plakio/uptime/master/assets/plak-icon.svg
  name: Plak
  introTitle: "Estado de los servicios de Plak"
  introMessage: Data en tiempo real e histórica del rendimiento de los sistemas de Plak
  navbar:
    - title: Status
      href: /
    - title: Soporte
      href: https://soporte.plak.io/


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
